before:
  hooks:
    - go mod tidy

builds:
  - binary: domru
    id: main-build
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

kos:
  - repository: ghcr.io/moleus/domru
    id: "github"
    build: "main-build"
    main: .
    base_image: "gcr.io/distroless/static-debian12"
    tags:
      - '{{.Version}}'
    bare: true
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
      - "linux/arm64"
      - "linux/arm/v7"
