version: "3.7"

services:
  domru:
    build:
      context: "."
      dockerfile: Dockerfile
    image: moleus/domru-dev:latest
    container_name: domru
    restart: always
    networks:
      - domru-net
    ports:
      - ${DOMRU_HOST_PORT:-8080}:18000
    environment:
      - DOMRU_PORT=18000
    volumes:
      - ./accounts.json:/share/domofon/accounts.json

networks:
  domru-net:
    name: domru-net
    driver: bridge
