services:
  domru:
    image: ghcr.io/moleus/domru:0.2.7-dev.0
    container_name: domru
    restart: always
    networks:
      - domru-net
    ports:
      - ${DOMRU_HOST_PORT:-8080}:18000
    environment:
      DOMRU_PORT: 18000
      LOG_LEVEL: debug
    volumes:
      - type: bind
        source: ./accounts.json
        target: /share/domofon/accounts.json

networks:
  domru-net:
    name: domru-net
    driver: bridge
