---
name: Build & publish docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev

permissions:
  packages: write
  pull-requests: read
  contents: read

env:
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
  KO_DEFAULTPLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  KO_DEFAULTBASEIMAGE: "gcr.io/distroless/static-debian12"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - run: go test ./...
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare -t devel-${{ env.BRANCH_NAME }}

  push_dockerhub:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1

      - uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/domru

      - env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo ${DOCKERHUB_TOKEN} | ko login --username=${DOCKERHUB_USERNAME} --password-stdin index.docker.io
          ko build --bare -t devel-${{ env.BRANCH_NAME }}
