---
name: Build & publish docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev

permissions:
  packages: write
  pull-requests: read
  contents: read

env:
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - run: go test ./...
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --platform=linux/amd64,linux/arm64 --bare -t devel-${{ env.BRANCH_NAME }}
