name: Build & publish docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev

env:
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --platform=linux/amd64,linux/arm64 --bare -t ${{ env.BRANCH_NAME }}
